tasks:

  - name: web-ui
    command: |
      unset JAVA_TOOL_OPTIONS
      clear
      echo "*********************"
      echo "** User Interface  **"
      echo "*********************"
      cd /workspace/cassandra-for-data-engineers/labs/lab2-user-interface/hotel-reviews-ui
      
  - name: setup
    before: |
      printf 'export PATH="$HOME%s:$PATH"\n' "/.astra/cli" >> $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      curl -Ls "https://dtsx.io/get-astra-cli" | bash >> ./install.log
    init: | 
      clear
      cd /workspace/cassandra-for-data-engineers
    command: |
      unset JAVA_TOOL_OPTIONS
      source /home/gitpod/.astra/cli/astra-init.sh
      clear
      echo "********************************************************"
      echo "** Welcome to training 'Cassandra for Data Engineer ***"
      echo "********************************************************"
       
ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
  
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false