UPDATE hotels_by_location SET thumbnail='https://privatecityhotels.com/en/wp-content/uploads/sites/3/Fassade-Tag0031831-1024x765.jpg'
WHERE uid=013f1b97-e848-423b-ba25-366c651e68eb
AND country='Austria'
AND city='Vienna';

UPDATE hotel_details SET thumbnail='https://privatecityhotels.com/en/wp-content/uploads/sites/3/Fassade-Tag0031831-1024x765.jpg'
WHERE uid=013f1b97-e848-423b-ba25-366c651e68eb;

UPDATE hotels_by_location 
SET thumbnail='https://www.austriacongress.com/_Resources/Persistent/b898d4cbdd3a8064bba12b55e05dc392dccc941c/Falkensteiner%20Hotel%20Wien%20Margareten%20-%20Aussenansicht%202%20%C2%A9%20Falkensteiner%20Hotels%20%26%20Residences-1920x1280.jpg'
WHERE uid=01800253-1eeb-45c2-bf35-cc25ccc745df
AND country='Austria'
AND city='Vienna';

UPDATE hotel_details 
SET thumbnail='https://www.austriacongress.com/_Resources/Persistent/b898d4cbdd3a8064bba12b55e05dc392dccc941c/Falkensteiner%20Hotel%20Wien%20Margareten%20-%20Aussenansicht%202%20%C2%A9%20Falkensteiner%20Hotels%20%26%20Residences-1920x1280.jpg'
WHERE uid=01800253-1eeb-45c2-bf35-cc25ccc745df

UPDATE hotels_by_location 
SET thumbnail='https://www.hotelgraben.at/fileadmin/user_upload/hotels/hotel-graben/04-ss-graben-hotel/graben_aussenansicht_edit_655x287.jpg'
WHERE uid=0242e82d-f507-45e1-a636-ec22fb992c03
AND country='Austria'
AND city='Vienna';

UPDATE hotel_details 
SET thumbnail='https://www.hotelgraben.at/fileadmin/user_upload/hotels/hotel-graben/04-ss-graben-hotel/graben_aussenansicht_edit_655x287.jpg'
WHERE uid=0242e82d-f507-45e1-a636-ec22fb992c03;

UPDATE hotels_by_location 
SET thumbnail='https://kidslovevienna.com/wp-content/uploads/user-uploads/Arthotel%20ANA%20Amadeus%20Vienna%20Inner%20City%20004.jpg'
WHERE uid=049ae50a-e26b-4d5d-9143-2251e8658307
AND country='Austria'
AND city='Vienna';

UPDATE hotel_details 
SET thumbnail='https://kidslovevienna.com/wp-content/uploads/user-uploads/Arthotel%20ANA%20Amadeus%20Vienna%20Inner%20City%20004.jpg'
WHERE uid=049ae50a-e26b-4d5d-9143-2251e8658307;

UPDATE hotels_by_location 
SET thumbnail='https://www.worldrainbowhotels.com/wp-content/uploads/2020/03/25hours-Hotel-at-MuseumsQuartier.jpg'
WHERE uid=0c2ab201-80c6-4158-a9e6-fefaab520e45
AND country='Austria'
AND city='Vienna';

UPDATE hotel_details 
SET thumbnail='https://www.worldrainbowhotels.com/wp-content/uploads/2020/03/25hours-Hotel-at-MuseumsQuartier.jpg'
WHERE uid=0c2ab201-80c6-4158-a9e6-fefaab520e45;

UPDATE hotels_by_location 
SET thumbnail='https://www.jet2holidays.com/HotelImages/Web/VIE_82673_Steigenberger_Hotel_Herronhof_0121_07.jpg'
WHERE uid=0c4e92f0-9fcb-4ce1-89f4-a6a6987f0ff2
AND country='Austria'
AND city='Vienna';

UPDATE hotel_details 
SET thumbnail='https://www.jet2holidays.com/HotelImages/Web/VIE_82673_Steigenberger_Hotel_Herronhof_0121_07.jpg'
WHERE uid=0c4e92f0-9fcb-4ce1-89f4-a6a6987f0ff2;

UPDATE hotels_by_location 
SET thumbnail='https://intern.rtk.at/uploads/139b4c9f-ca0d-4621-90f8-8c7e6a928816/aussen1_e6a0507.jpg'
WHERE uid=0d195799-1d48-4c5c-bcb3-3194f92f43ae
AND country='Austria'
AND city='Vienna';

UPDATE hotels_by_location 
SET thumbnail='https://i.ytimg.com/vi/RbS0fyf4qac/maxresdefault.jpg'
WHERE uid=0dc6e7fc-8fb9-4b0f-8f30-f97d268fec12
AND country='Austria'
AND city='Vienna';

UPDATE hotels_by_location 
SET thumbnail='https://suite-hotel-900-m-zur-oper.hotelsinvienna.org/data/Photos/767x430/1096/109685/109685718.JPEG'
WHERE uid=0eda9fba-90af-4afe-b11c-78f899372b56
AND country='Austria'
AND city='Vienna';
 
UPDATE hotels_by_location 
SET thumbnail='https://safereach.com/en/wp-content/uploads/sites/4/2020/05/InterContinental-Wien.jpg'
WHERE uid=14954d3f-c76c-433c-8d14-f3ef634bcc7a
AND country='Austria'
AND city='Vienna';








